server:
  port: 8010
# 日志配置
logging:
  level:
    com.cloud: info
    org.springframework: warn
spring:
  application:
    name: cloud-gen
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: nacos.khaos.cosmoplat.com:80
feign:
  hystrix:
    enabled: true
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    enabled: false
  okhttp:
    enabled: true


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cloud
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

mapper:
  not-empty: true
  identity: MYSQL

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
