### web
server:
  port: 8080
  servlet:
    context-path: /job

### actuator
management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: cloud-job-admin
  profiles:
    active: dev
    devtools:
      restart:
        enabled: true
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
### resources
  resources:
    static-locations: classpath:/static/
### freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
### datasource-pool
### xxl-job, datasource
  datasource:
    url: jdbc:mysql://10.133.116.86:3306/rycloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: cloud
    password: Cloud,123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 900000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  ### xxl-job, email
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    password: xxx
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory


### mybatis
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml


### xxl-job, access token
xxl:
  job:
    accessToken:
### xxl-job, i18n (default is zh_CN, and you can choose "zh_CN", "zh_TC" and "en")
    i18n: zh_CN

## xxl-job, triggerpool max size
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
### xxl-job, log retention days
    logretentiondays: 30
