
package com.cloud.settle.webService.gems;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "IfBaseClaim_Srv", targetNamespace = "http://gems.haier.com/IfBaseClaim_Srv", wsdlLocation = "http://10.133.28.51:8001/gems/services/baseClaim/ifBaseClaim_Srv?wsdl")
public class IfBaseClaimSrv extends Service {

    private final static URL IFBASECLAIMSRV_WSDL_LOCATION;
    private final static WebServiceException IFBASECLAIMSRV_EXCEPTION;
    private final static QName IFBASECLAIMSRV_QNAME = new QName("http://gems.haier.com/IfBaseClaim_Srv", "IfBaseClaim_Srv");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.133.28.51:8001/gems/services/baseClaim/ifBaseClaim_Srv?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IFBASECLAIMSRV_WSDL_LOCATION = url;
        IFBASECLAIMSRV_EXCEPTION = e;
    }

    public IfBaseClaimSrv() {
        super(__getWsdlLocation(), IFBASECLAIMSRV_QNAME);
    }

    public IfBaseClaimSrv(WebServiceFeature... features) {
        super(__getWsdlLocation(), IFBASECLAIMSRV_QNAME, features);
    }

    public IfBaseClaimSrv(URL wsdlLocation) {
        super(wsdlLocation, IFBASECLAIMSRV_QNAME);
    }

    public IfBaseClaimSrv(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IFBASECLAIMSRV_QNAME, features);
    }

    public IfBaseClaimSrv(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IfBaseClaimSrv(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns IfBaseClaimService
     */
    @WebEndpoint(name = "IfBaseClaimPort")
    public IfBaseClaimService getIfBaseClaimPort() {
        return super.getPort(new QName("http://gems.haier.com/IfBaseClaim_Srv", "IfBaseClaimPort"), IfBaseClaimService.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns IfBaseClaimService
     */
    @WebEndpoint(name = "IfBaseClaimPort")
    public IfBaseClaimService getIfBaseClaimPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gems.haier.com/IfBaseClaim_Srv", "IfBaseClaimPort"), IfBaseClaimService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IFBASECLAIMSRV_EXCEPTION != null) {
            throw IFBASECLAIMSRV_EXCEPTION;
        }
        return IFBASECLAIMSRV_WSDL_LOCATION;
    }

}
