
package com.cloud.settle.webService.gems;

import com.cloud.settle.domain.webServicePO.BaseClaimResponse;
import com.cloud.settle.domain.webServicePO.BaseMultiItemClaimSaveRequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "IfBaseClaimService", targetNamespace = "http://gems.haier.com/IfBaseClaim_Srv")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IfBaseClaimService {

    /**
     * @param baseMultiItemClaimSaveRequest
     * @return returns com.haier.gems.ifbaseclaim_srv.BaseClaimResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createMultiItemClaim", targetNamespace = "http://gems.haier.com/IfBaseClaim_Srv", className = "com.haier.gems.ifbaseclaim_srv.CreateMultiItemClaim")
    @ResponseWrapper(localName = "createMultiItemClaimResponse", targetNamespace = "http://gems.haier.com/IfBaseClaim_Srv", className = "com.haier.gems.ifbaseclaim_srv.CreateMultiItemClaimResponse")
    public BaseClaimResponse createMultiItemClaim(
            @WebParam(name = "baseMultiItemClaimSaveRequest", targetNamespace = "")
                    BaseMultiItemClaimSaveRequest baseMultiItemClaimSaveRequest);


}
