cloud:
  job:
    admin:
      addresses: http://orw-job.khaos.cosmoplat.com/job
    accessToken:
    executor:
      appname: cloud-job-executor
      address:
      ip:
      port: 9999
      logpath: /logs/jobhandler
      logretentiondays: 30
spring:
  redis:
    database: 1
    password: Cos8_Order    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    sentinel:
      master: cosorder
      nodes:
        - 10.202.89.21:16379
        - 10.202.89.22:16379
        - 10.202.89.23:16379
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  cloud:
    nacos:
      discovery:
        namespace: orw-prod
