server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.133.1.8:8848
        namespace: 071c0d1f-c1a4-48cc-ac1e-aa26e230309d

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
  application:
    name: cloud-job-executor
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

  # log config
logging:
  config: classpath:logback-spring.xml

feign:
  hystrix:
    enabled: true
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    enabled: false
  okhttp:
    enabled: true

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 80000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 20000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000 #断路器超时时间，默认1000ms

