cloud:
  job:
    admin:
      addresses: http://10.133.1.8:8081/job
    accessToken:
    executor:
      appname: cloud-job-executor
      address:
      ip:
      port: 9999
      logpath: /logs/jobhandler
      logretentiondays: 30
