server:
  port: 8081
spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true



  # log config
logging:
  config: classpath:logback.xml


cloud:
  job:
    admin:
      addresses: http://127.0.0.1:8080/job
    accessToken:
    executor:
      appname: cloud-job-executor
      address: http://127.0.0.1:9999
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

