spring:
  redis:
    database: 1
    host: 10.133.116.85
    port: 6379
    password: swyl2020     # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  cloud:
    nacos:
      discovery:
        namespace: 071c0d1f-c1a4-48cc-ac1e-aa26e230309d
uuc:
  apiUrl: http://uuctest.cosmoplat.com
  clientId: ZKDDPS
  clientSecret: 5b638080ef2c95fc8efec2599f7afa86
  isCheck: false
huc:
  apiUrl: https://tuser.haier.net:8182
  appKey: ZKDDPS
  secret: 131665df773d7b7b9b816fb46d7569ec
  isCheck: false
seata:
  registry:
    nacos:
      namespace: 071c0d1f-c1a4-48cc-ac1e-aa26e230309d
ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 80000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 20000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 100000 #断路器超时时间，默认1000ms

