
package com.cloud.order.webService.wms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RfWebServiceImplService", targetNamespace = "http://controller.rf.web.hand.ws.cosmo.haier.com/", wsdlLocation = "http://10.133.28.73:10001/epghand/soap/epgrf?wsdl")
public class RfWebServiceImplService
    extends Service
{

    private final static URL RFWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RFWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RFWEBSERVICEIMPLSERVICE_QNAME = new QName("http://controller.rf.web.hand.ws.cosmo.haier.com/", "RfWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.133.28.73:10001/epghand/soap/epgrf?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RFWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RFWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RfWebServiceImplService() {
        super(__getWsdlLocation(), RFWEBSERVICEIMPLSERVICE_QNAME);
    }

    public RfWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RFWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public RfWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RFWEBSERVICEIMPLSERVICE_QNAME);
    }

    public RfWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RFWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public RfWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RfWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RfWebService
     */
    @WebEndpoint(name = "RfWebServiceImplPort")
    public RfWebService getRfWebServiceImplPort() {
        return super.getPort(new QName("http://controller.rf.web.hand.ws.cosmo.haier.com/", "RfWebServiceImplPort"), RfWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RfWebService
     */
    @WebEndpoint(name = "RfWebServiceImplPort")
    public RfWebService getRfWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.rf.web.hand.ws.cosmo.haier.com/", "RfWebServiceImplPort"), RfWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RFWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RFWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return RFWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
