server:
  port: 8004
# 日志配置
logging:
  level:
    com.cloud: debug
    org.springframework: warn
    com.alibaba.nacos.client.naming: error

spring:
  application:
    name: cloud-activiti
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://10.133.116.86:3306/rycloud?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: cloud
    password: Cloud,123456
  cloud:
    nacos:
      discovery:
        server-addr: 10.133.1.8:8848
  activiti:
    check-process-definitions: false


feign:
  hystrix:
    enabled: true
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
    enabled: false
  okhttp:
    enabled: true


# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cloud
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

mapper:
  not-empty: true
  identity: MYSQL

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# seata配置,分布式事务
seata:
  enabled: true
  application-id: ${spring.application.name}
  #事务组
  tx-service-group: seataGroup-${seata.application-id}
  service:
    vgroup-mapping: 'default'
  #nacos中server-Addr 所在的命名空间
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
